# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: 'Windows-latest'
   name: PECOE-self-hosted
   demands:
     - Agent.Name -equals PWA-W01VUGEN13
     #AAMEAD1CUWDA02

steps:

- powershell: |
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-win64.tar.gz -OutFile $(System.DefaultWorkingDirectory)/codeql-bundle-win64.tar.gz
    tar -xvzf $(System.DefaultWorkingDirectory)/codeql-bundle-win64.tar.gz
    mkdir $(Agent.BuildDirectory)/s/codeql/codeql-dbs
  displayName: 'Download Codeql CLI package'

- powershell: |
        $(Agent.BuildDirectory)/s/codeql/codeql database create $(Agent.BuildDirectory)/s/codeql/codeql-dbs/Sec-demo-java-repo --language=java --command="mvn compile -DskipTests" --source-root=.
  displayName: 'Configure codeql database'

- powershell: |
    $(Agent.BuildDirectory)/s/codeql/codeql database analyze $(Agent.BuildDirectory)/s/codeql/codeql-dbs/Sec-demo-java-repo java-code-scanning.qls --sarif-category=java --format=sarif-latest --output=$(Agent.TempDirectory)/Sec-demo-java-repo.sarif
  displayName: 'Analyze codeql database'

# - script: |
#     echo "$token" | $(Agent.BuildDirectory)/s/codeql/codeql github upload-results --repository=Mariselvam-T/securityPOC-demo-java \
#     --ref=refs/heads/main \
#     --sarif=$(Agent.TempDirectory)/Sec-demo-java-repo.sarif --github-auth-stdin
#   env:
#     token: $(gh.token)
#   displayName: 'Upload results to Github'

- powershell:
  displayName: Upload CodeQL results to Github
    script:echo $(TOKEN) | $(System.DefaultWorkingDirectory)/codeql/codeql github upload-results --repository=Mariselvam-T/securityPOC-demo-java --ref=refs/heads/main --sarif=$(Agent.TempDirectory)/Sec-demo-java-repo.sarif --github-auth-stdin"
  env:
    TOKEN : $(gh.token)